services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ckhub
      POSTGRES_PASSWORD: ckhub
      POSTGRES_DB: ckhubapi
    ports:
      - "5433:5432"
    volumes:
      - ckhubapi_data:/var/lib/postgresql/data
    networks:
      ckhubapi-network:
        aliases:
          - ckhubapi-postgres-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ckhub -d ckhubapi"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
      start_interval: 3s
    labels:
      - "com.coursekata.service=database"
      - "com.coursekata.environment=development"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567:4566"
    environment:
      DEBUG: "0"
    volumes:
      - ckhubapi_localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ckhubapi-network:
        aliases:
          - ckhubapi-localstack
    restart: unless-stopped
    labels:
      - "com.coursekata.service=aws-mock"
      - "com.coursekata.environment=development"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ckhubapi-network
    restart: unless-stopped
    labels:
      - "com.coursekata.service=api"
      - "com.coursekata.environment=development"

volumes:
  ckhubapi_data:
    driver: local
  ckhubapi_localstack_data:
    driver: local
networks:
  ckhubapi-network:
    driver: bridge
