[project]
name = "sharing-service"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[tasks]
build = "./init-local-stack.sh && gradle wrapper && ./gradlew build"
start = "docker-compose --profile api up --build"
start-services = "docker-compose up"
stop = "docker-compose --profile api down"
test = "./gradlew test"
coverage = "./gradlew jacocoTestReport"
clean = "./gradlew clean"

[dependencies]
docker-compose = ">=2.30.3,<3"
awscli-local = ">=0.22.0,<0.23"
openjdk = "17.*"
gradle = ">=8.11.1,<9"
python = ">=3.11.0,<3.14"
nbformat = ">=5.10.4,<6"
